blank_issues_enabled: false
contact_links:
  - name: Jira Ticket
    url: https://myrealtrip.atlassian.net/jira/software/c/projects/FLIGHT/boards/226
    about: Create a Jira ticket for the FLIGHT project.
